import React, { useState, useEffect } from 'react';
import { useRuntimeStore } from './interpreter';
import { AppAST, PageModel, EntitySchema, FieldSchema } from '@/schemas/compiler';
import {
  LayoutDashboard,
  Table,
  Settings,
  Database,
  Shield,
  User,
  Plus,
  Edit2,
  Trash2,
  AlertTriangle,
  CheckCircle,
  Eye,
  Terminal,
  Activity,
  FileCode,
  Check,
  Search,
  XCircle
} from 'lucide-react';

interface SandboxProps {
  ast: AppAST;
}

export function VirtualSandboxRenderer({ ast }: SandboxProps) {
  // Store reference to AST on window for the store to read during API calls
  useEffect(() => {
    (window as any).__compiler_ast = ast;
  }, [ast]);

  const {
    db,
    currentUser,
    logs,
    initializeRuntime,
    setCurrentUser,
    insertRow,
    updateRow,
    deleteRow,
    selectRows,
    clearLogs
  } = useRuntimeStore();

  const [activePageId, setActivePageId] = useState<string>('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<'create' | 'edit'>('create');
  const [selectedRowId, setSelectedRowId] = useState<string | null>(null);
  const [formValues, setFormValues] = useState<Record<string, any>>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [sandboxNotification, setSandboxNotification] = useState<{
    type: 'success' | 'error';
    message: string;
  } | null>(null);
  const [showSuccessBanner, setShowSuccessBanner] = useState(false);
  const [prevAst, setPrevAst] = useState<AppAST | null>(null);

  // Trigger Generated Application Ready banner when AST changes
  useEffect(() => {
    if (ast && ast !== prevAst) {
      setShowSuccessBanner(true);
      setPrevAst(ast);
      const timer = setTimeout(() => setShowSuccessBanner(false), 5000);
      return () => clearTimeout(timer);
    }
  }, [ast, prevAst]);

  // Auto-dismiss banner after 4 seconds
  useEffect(() => {
    if (sandboxNotification) {
      const timer = setTimeout(() => setSandboxNotification(null), 4000);
      return () => clearTimeout(timer);
    }
  }, [sandboxNotification]);

  // Re-initialize runtime db if AST changes
  useEffect(() => {
    initializeRuntime(ast);
    if (ast && ast.architecture && ast.architecture.pages && ast.architecture.pages.length > 0) {
      setActivePageId(ast.architecture.pages[0].id);
    }
  }, [ast, initializeRuntime]);

  const pages = ast?.architecture?.pages || [];
  const activePage = pages.find(p => p.id === activePageId) || pages[0];

  if (!activePage) {
    return (
      <div className="flex items-center justify-center h-96 text-slate-400">
        No pages configured in architecture model.
      </div>
    );
  }

  // Get active roles
  const roles = ast.permissions.roles;

  // Handles switching role
  const handleRoleChange = (roleName: string) => {
    const mockUsers = db['User'] || [];
    const matchedUser = mockUsers.find(u => u.role === roleName);
    if (matchedUser) {
      setCurrentUser(matchedUser);
    } else {
      setCurrentUser({
        id: `usr-${Date.now()}`,
        name: `Guest ${roleName}`,
        role: roleName
      });
    }
  };

  const handleOpenCreateModal = () => {
    if (!activePage.entity) return;
    const entitySchema = ast.schema.entities[activePage.entity];
    if (!entitySchema) return;

    // Build default values
    const defaults: Record<string, any> = {};
    Object.entries(entitySchema.fields).forEach(([name, field]) => {
      if (field.primaryKey) {
        defaults[name] = ''; // Autogenerated
      } else {
        defaults[name] = field.defaultValue !== undefined ? field.defaultValue : '';
      }
    });

    setFormValues(defaults);
    setFormError(null);
    setModalMode('create');
    setIsModalOpen(true);
  };

  const handleOpenEditModal = (row: any) => {
    if (!activePage.entity) return;
    const entitySchema = ast.schema.entities[activePage.entity];
    if (!entitySchema) return;

    const pkField = Object.keys(entitySchema.fields).find(k => entitySchema.fields[k].primaryKey) || 'id';
    setSelectedRowId(row[pkField]);
    setFormValues({ ...row });
    setFormError(null);
    setModalMode('edit');
    setIsModalOpen(true);
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!activePage.entity) return;

    const entityName = activePage.entity;
    let res;

    if (modalMode === 'create') {
      res = insertRow(entityName, formValues);
    } else {
      res = updateRow(entityName, selectedRowId!, formValues);
    }

    if (res.success) {
      setIsModalOpen(false);
      setFormError(null);
      setSandboxNotification({
        type: 'success',
        message: `Database entry for "${entityName}" successfully ${modalMode === 'create' ? 'created' : 'updated'}.`
      });
    } else {
      setFormError(res.error || 'Operation failed');
    }
  };

  const handleDelete = (row: any) => {
    if (!activePage.entity) return;
    const entitySchema = ast.schema.entities[activePage.entity];
    if (!entitySchema) return;
    const pkField = Object.keys(entitySchema.fields).find(k => entitySchema.fields[k].primaryKey) || 'id';

    const res = deleteRow(activePage.entity, row[pkField]);
    if (!res.success) {
      setSandboxNotification({
        type: 'error',
        message: res.error || 'Referential integrity violation or permission denied.'
      });
    } else {
      setSandboxNotification({
        type: 'success',
        message: `Database record from table "${activePage.entity}" successfully deleted.`
      });
    }
  };

  // Render forms dynamic inputs
  const renderFormInputs = () => {
    if (!activePage.entity) return null;
    const entitySchema = ast.schema.entities[activePage.entity];
    if (!entitySchema) return null;

    return Object.entries(entitySchema.fields).map(([name, field]) => {
      if (field.primaryKey && modalMode === 'create') {
        return (
          <div key={name} className="mb-4">
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wide mb-1">
              {name} (Primary Key)
            </label>
            <input
              type="text"
              disabled
              placeholder="Autogenerated UUID"
              className="w-full px-3 py-2 bg-slate-900/50 border border-slate-700 rounded-md text-sm text-slate-500 cursor-not-allowed font-mono"
            />
          </div>
        );
      }

      if (field.primaryKey && modalMode === 'edit') {
        return (
          <div key={name} className="mb-4">
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wide mb-1">
              {name}
            </label>
            <input
              type="text"
              disabled
              value={formValues[name] || ''}
              className="w-full px-3 py-2 bg-slate-900/50 border border-slate-700 rounded-md text-sm text-slate-500 cursor-not-allowed font-mono"
            />
          </div>
        );
      }

      // Foreign Key dropdown selector
      if (field.foreignKey) {
        const targetTable = db[field.foreignKey.entity] || [];
        const targetPk = field.foreignKey.field;
        return (
          <div key={name} className="mb-4">
            <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wide mb-1">
              {name} (Relation: {field.foreignKey.entity}) {field.required && <span className="text-rose-500">*</span>}
            </label>
            <select
              value={formValues[name] || ''}
              onChange={e => setFormValues({ ...formValues, [name]: e.target.value })}
              className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-md text-sm text-slate-100 focus:outline-none focus:border-indigo-500"
              required={field.required}
            >
              <option value="">Select referenced record</option>
              {targetTable.map(targetRow => {
                const labelField = Object.keys(targetRow).find(k => k.toLowerCase().includes('name') || k.toLowerCase().includes('title')) || targetPk;
                return (
                  <option key={targetRow[targetPk]} value={targetRow[targetPk]}>
                    {targetRow[labelField]} ({targetRow[targetPk]})
                  </option>
                );
              })}
            </select>
          </div>
        );
      }

      // Standard types input mappings
      if (field.type === 'enum' && field.enumValues) {
        return (
          <div key={name} className="mb-4">
            <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wide mb-1">
              {name} {field.required && <span className="text-rose-500">*</span>}
            </label>
            <select
              value={formValues[name] || ''}
              onChange={e => setFormValues({ ...formValues, [name]: e.target.value })}
              className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-md text-sm text-slate-100 focus:outline-none focus:border-indigo-500"
              required={field.required}
            >
              <option value="">Select option</option>
              {field.enumValues.map(opt => (
                <option key={opt} value={opt}>{opt}</option>
              ))}
            </select>
          </div>
        );
      }

      if (field.type === 'boolean') {
        return (
          <div key={name} className="flex items-center mb-4 mt-2">
            <input
              type="checkbox"
              id={`field-${name}`}
              checked={!!formValues[name]}
              onChange={e => setFormValues({ ...formValues, [name]: e.target.checked })}
              className="h-4 w-4 rounded border-slate-700 bg-slate-800 text-indigo-600 focus:ring-indigo-500 focus:ring-offset-slate-900"
            />
            <label htmlFor={`field-${name}`} className="ml-2 block text-sm text-slate-300 font-medium">
              {name}
            </label>
          </div>
        );
      }

      return (
        <div key={name} className="mb-4">
          <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wide mb-1">
            {name} {field.required && <span className="text-rose-500">*</span>}
          </label>
          <input
            type={field.type === 'number' ? 'number' : field.type === 'date' ? 'date' : 'text'}
            value={formValues[name] || ''}
            onChange={e => setFormValues({ ...formValues, [name]: e.target.value })}
            className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-md text-sm text-slate-100 focus:outline-none focus:border-indigo-500"
            required={field.required}
          />
        </div>
      );
    });
  };

  // Perform filtering/select based on active permissions and search
  const renderCRUDPage = (page: PageModel) => {
    if (!page.entity) return null;
    const entityName = page.entity;
    const entitySchema = ast.schema.entities[entityName];
    if (!entitySchema) {
      return (
        <div className="flex flex-col items-center justify-center p-12 text-slate-400 bg-slate-900/30 rounded-lg border border-slate-800">
          <AlertTriangle className="h-10 w-10 text-amber-500 mb-2" />
          Schema definition for &quot;{entityName}&quot; is missing. Run repair or schema compiler.
        </div>
      );
    }

    const rows = selectRows(entityName);
    const fields = Object.values(entitySchema.fields);
    
    // Apply search filter
    const filteredRows = rows.filter(row => {
      if (!searchQuery) return true;
      return Object.values(row).some(val => 
        String(val).toLowerCase().includes(searchQuery.toLowerCase())
      );
    });

    return (
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4">
          <div className="relative flex-1 max-w-md">
            <span className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <Search className="h-4 w-4 text-slate-500" />
            </span>
            <input
              type="text"
              placeholder={`Search ${entityName}s...`}
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-slate-900 border border-slate-800 rounded-lg text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 transition"
            />
          </div>
          <button
            onClick={handleOpenCreateModal}
            className="flex items-center gap-1.5 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-semibold transition"
          >
            <Plus className="h-4 w-4" />
            Add {entityName}
          </button>
        </div>

        <div className="overflow-x-auto border border-slate-800 bg-slate-900/20 rounded-xl">
          <table className="w-full text-left text-sm text-slate-300">
            <thead className="bg-slate-900/50 text-slate-400 font-semibold border-b border-slate-800">
              <tr>
                {fields.map(f => (
                  <th key={f.name} className="px-6 py-4 font-medium uppercase tracking-wider text-xs">
                    {f.name}
                  </th>
                ))}
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {filteredRows.length === 0 ? (
                <tr>
                  <td colSpan={fields.length + 1} className="text-center py-12 text-slate-500 font-medium">
                    No records found matching current session rules.
                  </td>
                </tr>
              ) : (
                filteredRows.map((row, idx) => {
                  const pkField = fields.find(f => f.primaryKey)?.name || 'id';
                  const rowId = row[pkField];
                  return (
                    <tr key={idx} className="hover:bg-slate-900/30 transition">
                      {fields.map(f => {
                        let cellVal = row[f.name];
                        if (typeof cellVal === 'boolean') {
                          cellVal = cellVal ? (
                            <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">True</span>
                          ) : (
                            <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-slate-500/10 text-slate-400 border border-slate-500/20">False</span>
                          );
                        } else if (f.foreignKey && cellVal) {
                          // Display a relations badge link
                          cellVal = (
                            <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-mono bg-violet-500/10 text-violet-400 border border-violet-500/20">
                              {cellVal}
                            </span>
                          );
                        } else if (f.type === 'enum') {
                          cellVal = (
                            <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-500/10 text-blue-400 border border-blue-500/20">
                              {cellVal}
                            </span>
                          );
                        }
                        return (
                          <td key={f.name} className="px-6 py-4 font-medium whitespace-nowrap">
                            {cellVal}
                          </td>
                        );
                      })}
                      <td className="px-6 py-4 text-right space-x-2">
                        <button
                          onClick={() => handleOpenEditModal(row)}
                          className="p-1.5 hover:bg-slate-800 text-indigo-400 hover:text-indigo-300 rounded-md transition"
                        >
                          <Edit2 className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(row)}
                          className="p-1.5 hover:bg-slate-800 text-rose-400 hover:text-rose-300 rounded-md transition"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    );
  };

  const renderDashboardPage = (page: PageModel) => {
    return (
      <div className="space-y-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {page.components.map(compId => {
            const comp = ast.architecture.components.find(c => c.id === compId);
            if (!comp) return null;

            if (comp.type === 'stats' && comp.entity) {
              const rows = db[comp.entity] || [];
              return (
                <div key={compId} className="p-6 bg-slate-900 border border-slate-800 rounded-xl relative overflow-hidden shadow-sm">
                  <div className="absolute right-4 top-4 text-slate-800">
                    <Database className="h-10 w-10" />
                  </div>
                  <h3 className="text-slate-400 text-sm font-semibold uppercase tracking-wider">{comp.name}</h3>
                  <div className="text-4xl font-extrabold text-white mt-2">{rows.length}</div>
                  <p className="text-slate-500 text-xs mt-2">Binds to table: &ldquo;{comp.entity}&rdquo;</p>
                </div>
              );
            }

            if (comp.type === 'chart' && comp.entity) {
              const rows = db[comp.entity] || [];
              return (
                <div key={compId} className="p-6 bg-slate-900 border border-slate-800 rounded-xl col-span-1 md:col-span-2">
                  <h3 className="text-slate-400 text-sm font-semibold uppercase tracking-wider mb-4">{comp.name}</h3>
                  {rows.length === 0 ? (
                    <div className="h-32 flex items-center justify-center text-slate-500 text-sm">
                      No data to chart. Add records to {comp.entity}.
                    </div>
                  ) : (
                    <div className="flex items-end justify-around h-32 pt-4 border-b border-l border-slate-800">
                      {rows.map((r, i) => (
                        <div key={i} className="flex flex-col items-center w-8">
                          <div 
                            className="w-full bg-gradient-to-t from-indigo-600 to-indigo-400 rounded-t"
                            style={{ height: `${Math.min(100, Math.max(20, (i + 1) * 30))}px` }}
                          />
                          <span className="text-[10px] text-slate-500 mt-1 truncate max-w-full">
                            {r.name || r.title || `Row ${i}`}
                          </span>
                        </div>
                      ))}
                    </div>
                  )}
                  <p className="text-slate-500 text-[10px] mt-3">Simulation generated based on {comp.entity} schema</p>
                </div>
              );
            }

            return (
              <div key={compId} className="p-6 bg-slate-900 border border-slate-800 rounded-xl">
                <h3 className="text-slate-400 text-sm font-semibold uppercase tracking-wider">{comp.name}</h3>
                <div className="text-slate-500 text-sm mt-4">Generic UI component placeholder ({comp.type})</div>
              </div>
            );
          })}
        </div>
      </div>
    );
  };

  return (
    <div className="min-h-[500px] flex flex-col lg:flex-row bg-slate-950 text-slate-100 rounded-2xl border border-slate-800 overflow-hidden">
      
      {/* 1. RUNTIME SIDEBAR */}
      <div className="w-full lg:w-64 bg-slate-900 border-r border-slate-800 p-6 flex flex-col justify-between gap-6 shrink-0">
        <div className="space-y-6">
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 bg-indigo-600 rounded-lg flex items-center justify-center font-bold text-white shadow-md">
              R
            </div>
            <div>
              <h2 className="font-bold text-sm tracking-tight text-white leading-tight">{ast.appName}</h2>
              <span className="text-[10px] text-slate-500 uppercase tracking-widest font-bold">Virtual Interpreter</span>
            </div>
          </div>

          <nav className="space-y-1.5">
            {pages.map(page => {
              const isActive = activePage.id === page.id;
              return (
                <button
                  key={page.id}
                  onClick={() => setActivePageId(page.id)}
                  className={`w-full flex items-center gap-2.5 px-3.5 py-2.5 rounded-lg text-sm font-semibold transition ${
                    isActive
                      ? 'bg-indigo-600 text-white shadow-sm'
                      : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'
                  }`}
                >
                  {page.type === 'dashboard' ? (
                    <LayoutDashboard className="h-4 w-4" />
                  ) : (
                    <Table className="h-4 w-4" />
                  )}
                  {page.title}
                </button>
              );
            })}
          </nav>
        </div>

        {/* Dynamic Role Switcher */}
        <div className="p-4 bg-slate-950/60 rounded-xl border border-slate-800/80 space-y-3">
          <div className="flex items-center gap-1.5 text-xs text-slate-400 font-semibold uppercase tracking-wider">
            <Shield className="h-3.5 w-3.5 text-indigo-400" />
            <span>Active Session Role</span>
          </div>
          <select
            value={currentUser?.role || ''}
            onChange={e => handleRoleChange(e.target.value)}
            className="w-full px-2.5 py-1.5 bg-slate-900 border border-slate-800 rounded-md text-xs font-semibold text-white focus:outline-none focus:border-indigo-500"
          >
            {roles.map(r => (
              <option key={r} value={r}>{r}</option>
            ))}
          </select>
          <div className="flex items-center gap-1.5 text-[10px] text-slate-500 font-medium">
            <User className="h-3 w-3 text-slate-600" />
            <span className="truncate">{currentUser?.name || 'Guest'}</span>
          </div>
        </div>
      </div>

      {/* 2. PAGE CONTENT VIEW */}
      <div className="flex-1 flex flex-col overflow-hidden">
        
        {/* Header toolbar */}
        <header className="px-8 py-5 border-b border-slate-800 bg-slate-900/30 flex justify-between items-center gap-6">
          <div>
            <h1 className="text-xl font-bold tracking-tight text-white">{activePage.title}</h1>
            <p className="text-xs text-slate-500 mt-0.5">Route: {activePage.route}</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="inline-flex h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest bg-slate-900 border border-slate-800 px-2 py-1 rounded">
              Sandbox Live
            </span>
          </div>
        </header>

        {/* Workspace body */}
        <main className="flex-1 p-8 overflow-y-auto space-y-4">
          {showSuccessBanner && (
            <div className="p-4 bg-gradient-to-r from-emerald-600 to-teal-600 border border-emerald-500/30 text-white rounded-xl shadow-lg shadow-emerald-500/10 flex items-center justify-between gap-4 animate-pulse">
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 bg-white/20 rounded-xl flex items-center justify-center shrink-0">
                  <CheckCircle className="h-6 w-6 text-white animate-bounce" />
                </div>
                <div>
                  <h4 className="font-extrabold text-sm tracking-tight">Generated Application Ready</h4>
                  <p className="text-xs opacity-90 mt-0.5 font-medium">
                    The Nexus compiler successfully generated database schemas, component structures, and active session roles.
                  </p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setShowSuccessBanner(false)}
                className="text-white/80 hover:text-white font-bold text-lg leading-none p-1.5 transition hover:scale-110 shrink-0"
              >
                &times;
              </button>
            </div>
          )}

          {sandboxNotification && (
            <div className={`p-4 rounded-xl border flex items-start gap-3 animate-fadeIn transition-all duration-300 ${
              sandboxNotification.type === 'error'
                ? 'bg-rose-500/10 border-rose-500/20 text-rose-400'
                : 'bg-emerald-500/10 border-emerald-500/20 text-emerald-450'
            }`}>
              <span className="mt-0.5">
                {sandboxNotification.type === 'error' ? (
                  <XCircle className="h-5 w-5 text-rose-500 shrink-0" />
                ) : (
                  <CheckCircle className="h-5 w-5 text-emerald-500 shrink-0" />
                )}
              </span>
              <div className="flex-1">
                <h4 className="font-bold text-xs uppercase tracking-wider text-slate-200">
                  {sandboxNotification.type === 'error' ? 'Transaction Failure' : 'Transaction Success'}
                </h4>
                <p className="text-xs text-slate-300 mt-1 font-medium leading-normal">{sandboxNotification.message}</p>
              </div>
              <button
                onClick={() => setSandboxNotification(null)}
                className="text-slate-500 hover:text-slate-300 text-xs font-bold font-mono transition"
              >
                &times;
              </button>
            </div>
          )}

          {activePage.type === 'dashboard'
            ? renderDashboardPage(activePage)
            : renderCRUDPage(activePage)}
        </main>
        
        {/* SQL & Console Log view */}
        <footer className="border-t border-slate-800 bg-slate-950 p-6 space-y-3 shrink-0 max-h-56 overflow-y-auto font-mono text-[11px]">
          <div className="flex justify-between items-center border-b border-slate-800/80 pb-2">
            <span className="text-slate-400 font-semibold uppercase tracking-wider text-[10px] flex items-center gap-1.5">
              <Terminal className="h-3.5 w-3.5 text-slate-500" />
              Relational DB Console Logs
            </span>
            <button
              onClick={clearLogs}
              className="text-[10px] text-slate-500 hover:text-slate-300 font-semibold transition"
            >
              Clear
            </button>
          </div>
          <div className="space-y-1">
            {logs.length === 0 ? (
              <span className="text-slate-600 italic">No logs recorded. Interact with the table models above.</span>
            ) : (
              logs.map((log, i) => (
                <div key={i} className="flex gap-4">
                  <span className="text-slate-500 select-none">[{log.timestamp}]</span>
                  <span className={`font-bold select-none ${log.status === 'success' ? 'text-emerald-500' : 'text-rose-500'}`}>
                    {log.action}
                  </span>
                  <span className={log.status === 'success' ? 'text-slate-300' : 'text-rose-400'}>
                    {log.message}
                  </span>
                </div>
              ))
            )}
          </div>
        </footer>
      </div>

      {/* 3. DYNAMIC MODAL FORM */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
          <div className="w-full max-w-lg bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-2xl">
            <header className="px-6 py-4 border-b border-slate-800 flex justify-between items-center">
              <h3 className="font-bold text-white text-base">
                {modalMode === 'create' ? 'Create New' : 'Edit'} {activePage.entity}
              </h3>
              <button
                onClick={() => setIsModalOpen(false)}
                className="text-slate-400 hover:text-slate-200 text-xl font-bold transition"
              >
                &times;
              </button>
            </header>
            
            <form onSubmit={handleFormSubmit}>
              <div className="p-6 max-h-[450px] overflow-y-auto">
                {formError && (
                  <div className="mb-4 p-3 bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs rounded-lg flex items-start gap-2">
                    <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5" />
                    <span>{formError}</span>
                  </div>
                )}
                
                {renderFormInputs()}
              </div>
              
              <footer className="px-6 py-4 border-t border-slate-800 bg-slate-900/50 flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 border border-slate-700 hover:bg-slate-800 rounded-lg text-sm text-slate-300 transition"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-semibold transition"
                >
                  {modalMode === 'create' ? 'Create' : 'Save Changes'}
                </button>
              </footer>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
